### ISSUE TITLE
QUESTION: How to submit a new Rails Example Application

### ISSUE THREAD

**Issue by MarkDBlackwell** [RailsApps/rails-composer#103]
The documentation seems vague about how to add (even how to approach requesting to add) a Rails Example Application to the list presented by Rails Composer.

Article [Rails Examples and Tutorials](http://railsapps.github.io/) says: "This is a website and [GitHub repository](https://github.com/RailsApps) for open source Ruby on Rails example applications." The article's subheading _Example Rails Applications_ contains a list of them.

Rails Composer README section [From the RailsApps Project](https://github.com/RailsApps/rails-composer/#from-the-railsapps-project) says: "The [RailsApps project](http://railsapps.github.io/) provides example applications that developers use as starter apps."

**Comment by Schwad** [comment]
Howdy @MarkDBlackwell  - if I'm reading your issue right, you could open up a pull request against the RailsApps/rails-composer repo with any additional example applications you wanted included into the mix? Or am I misreading your question?
