### ISSUE TITLE
Not getting prompt when installing RailsApp

### ISSUE THREAD

**Issue by stevchenks** [RailsApps/rails-composer#159]
Hi,

On generation of the RailsApp using: 
$ rails new myapp -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb

I am not getting the prompt asking which example app I wish to install, which means I'm just left with the basic rails setup...

Any help?

Thanks,

Ed

**Comment by TarikFojnica** [comment]
Hi,
Did you manage to find the solution since I'm facing the same issue. Using Ruby 2.2 and Rails 4.2. I'm not really experienced with Rails, just started with learning some of Your apps. I've also tried with other apps and the problem persists.

Thank you

**Comment by DanielKehoe** [comment]
Start with this guide:
http://railsapps.github.io/installing-rails.html
and see if your problems get resolved.

**Comment by TarikFojnica** [comment]
Thanks Daniel,
The problem was probably in my Windows development environment. I switched to a cloud, and followed https://github.com/RailsApps/rails-composer#creating-a-starter-app-using-rvm 
Now it's fine.
