### ISSUE TITLE
undefined local variable or method `invitation_token'

### ISSUE THREAD

**Issue by gabehoffman** [RailsApps/rails-composer#168]
I've tried this several times, and I keep getting an issue with these settings.  I'm just trying to make sure it's working so I'm logging in with the default user from the secrets.yml file, and it doesn't think it's been invited yet it would seem.  It does this even if I don't select Devise with the invitable modules. Do I have to sign up before I log in as admin or something?

Here's my readme info:

Recipes:
- apps4
- controllers
- core
- email
- extras
- frontend
- gems
- git
- init
- models
- prelaunch
- railsapps
- readme
- routes
- saas
- setup
- testing
- views

Preferences:
- git: true
- apps4: none
- dev_webserver: webrick
- prod_webserver: thin
- database: postgresql
- templates: erb
- unit_test: rspec
- integration: rspec-capybara
- continuous_testing: guard
- fixtures: factory_girl
- frontend: bootstrap3
- email: sendgrid
- authentication: devise
- devise_modules: confirmable
- authorization: pundit
- form_builder: simple_form
- starter_app: admin_app
- rvmrc: false
- better_errors: true
- ban_spiders: true

I'm running 
ruby 2.0.0p247
rails 4.1.0.rc1

**Comment by sonianand11** [comment]
@marcamillion Thank you. This fixes my issue.
