### ISSUE TITLE
Haml failure when generating rails-signup-download application

### ISSUE THREAD

**Issue by dannyvanhoof** [RailsApps/rails-composer#215]
When I generated the rails-signup-download application this morning, I got a crash in the third stage:

https://raw.github.com/RailsApps/rails-composer/master/composer.rb:224:in `html_to_slim': uninitialized constant Haml::HTML (NameError)

My entire creation log:

      remove    .gitignore
      create    .gitignore
         run    git init from "."
Initialized empty Git repository in /home/danny/Dropbox/workspace/cookbook/.git/
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: initial commit" from "."
      recipe  Running railsapps recipe...
      option  Build a starter application?
          1)  Build a RailsApps example application
          2)  Contributed applications (none available)
          3)  Custom application (experimental)
      choose  Enter your selection: 1
      option  Choose a starter application.
          1)  learn-rails
          2)  rails-bootstrap
          3)  rails-foundation
          4)  rails-mailinglist-activejob
          5)  rails-omniauth
          6)  rails-devise
          7)  rails-devise-roles
          8)  rails-devise-pundit
          9)  rails-signup-download
         10)  rails-stripe-checkout
         11)  rails-stripe-coupons
      choose  Enter your selection: 9
              Get on the mailing list for Rails Composer news?
      option  Enter your email address: 
      recipe  Running learn_rails recipe...
      recipe  Running rails_bootstrap recipe...
      recipe  Running rails_foundation recipe...
      recipe  Running rails_omniauth recipe...
      recipe  Running rails_devise recipe...
      recipe  Running rails_devise_roles recipe...
      recipe  Running rails_devise_pundit recipe...
      recipe  Running rails_signup_download recipe...
      recipe  Running rails_mailinglist_activejob recipe...
      recipe  Running rails_stripe_checkout recipe...
      recipe  Running rails_stripe_coupons recipe...
      recipe  Running setup recipe...
       setup  Your operating system is linux-gnu.
       setup  You are using Ruby version 2.2.0.
       setup  You are using Rails version 4.2.0.
      option  Web server for development?
          1)  WEBrick (default)
          2)  Thin
          3)  Unicorn
          4)  Puma
          5)  Phusion Passenger (Apache/Nginx)
          6)  Phusion Passenger (Standalone)
      choose  Enter your selection: 2
      option  Web server for production?
          1)  Same as development
          2)  Thin
          3)  Unicorn
          4)  Puma
          5)  Phusion Passenger (Apache/Nginx)
          6)  Phusion Passenger (Standalone)
      choose  Enter your selection: 2
      option  Database used in development?
          1)  SQLite
          2)  PostgreSQL
          3)  MySQL
      choose  Enter your selection: 2
      option  Template engine?
          1)  ERB
          2)  Haml
          3)  Slim
      choose  Enter your selection: 3
      option  Test framework?
          1)  None
          2)  RSpec with Capybara
      choose  Enter your selection: 2
       setup  Adding DatabaseCleaner, FactoryGirl, Faker, Launchy, Selenium
      option  Continuous testing?
          1)  None
          2)  Guard
      choose  Enter your selection: 1
      option  Front-end framework?
          1)  None
          2)  Bootstrap 3.3
          3)  Bootstrap 2.3
          4)  Zurb Foundation 5.5
          5)  Zurb Foundation 4.0
          6)  Simple CSS
      choose  Enter your selection: 2
       setup  The Devise 'forgot password' feature requires email.
      option  Add support for sending email?
          1)  None
          2)  Gmail
          3)  SMTP
          4)  SendGrid
          5)  Mandrill
      choose  Enter your selection: 5
      option  Admin interface for database?
          1)  None
          2)  Upmin
      choose  Enter your selection: 1
      create    README
      append    README
      recipe  Running locale recipe...
      recipe  Running readme recipe...
      recipe  Running gems recipe...
      insert    Gemfile
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: Gemfile" from "."
      recipe  Running tests recipe...
      recipe  Running email recipe...
      recipe  Running devise recipe...
      recipe  Running omniauth recipe...
      recipe  Running roles recipe...
      recipe  Running frontend recipe...
      recipe  Running pages recipe...
      recipe  Running init recipe...
      recipe  Running analytics recipe...
      option  Install page-view analytics?
          1)  None
          2)  Google Analytics
          3)  Segment.io
      choose  Enter your selection: 1
      recipe  Running deployment recipe...
      option  Prepare for deployment?
          1)  no
          2)  Heroku
          3)  Capistrano
      choose  Enter your selection: 2
  deployment  installing gems for Heroku
      recipe  Running extras recipe...
      option  Set a robots.txt file to ban spiders? (y/n) y
      option  Create a GitHub repository? (y/n) n
      option  Use or create a project-specific rvm gemset? (y/n) y
      extras  recipe creating project-specific rvm gemset and .rvmrc
      extras  creating RVM gemset 'cookbook'
      extras  switching to gemset 'cookbook'
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
      create    .ruby-version
      create    .ruby-gemset
      extras  recipe setting quiet_assets for reduced asset pipeline logging
      extras  recipe adding better_errors gem
      extras  recipe banning spiders by modifying 'public/robots.txt'
      option  Add 'therubyracer' JavaScript runtime (for Linux users without node.js)? (y/n) n
    composer  Installing gems. This will take a while.
         run    bundle install --without production from "."
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using addressable 2.3.7
Using execjs 2.3.0
Using autoprefixer-rails 5.1.5
Using bcrypt 3.1.10
Using coderay 1.1.0
Using better_errors 2.1.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using sass 3.4.11
Using bootstrap-sass 3.3.3
Using bundler 1.7.13
Using columnize 0.9.0
Using debugger-linecache 1.2.0
Using slop 3.6.0
Using byebug 3.5.1
Using xpath 2.0.0
Using capybara 2.4.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using ffi 1.9.6
Using childprocess 0.5.5
Using coffee-script-source 1.9.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Using coffee-rails 4.1.0
Using daemons 1.1.9
Using database_cleaner 1.4.0
Using orm_adapter 0.5.0
Using responders 2.1.0
Using warden 1.2.3
Using devise 3.4.1
Using diff-lcs 1.2.5
Using eventmachine 1.0.6
Using factory_girl 4.5.0
Using factory_girl_rails 4.5.0
Using faker 1.4.3
Using multi_xml 0.5.5
Using httparty 0.13.3
Using multi_json 1.10.1
Using gibbon 1.1.4
Using tilt 1.4.1
Using haml 4.0.6
Using sexp_processor 4.4.5
Using ruby_parser 3.6.4
Using haml2slim 0.4.7
Using hike 1.2.3
Using html2haml 2.0.0
Using jbuilder 2.2.6
Using jquery-rails 4.0.3
Using launchy 2.4.3
Using pg 0.18.1
Using quiet_assets 1.1.0
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rails_apps_pages 0.5.15
Using rails_apps_testing 0.3.12
Using rails_layout 1.0.24
Using rspec-support 3.2.1
Using rspec-core 3.2.0
Using rspec-expectations 3.2.0
Using rspec-mocks 3.2.0
Using rspec-rails 3.2.0
Using rubyzip 1.1.7
Using sass-rails 5.0.1
Using websocket 1.2.1
Using selenium-webdriver 2.44.0
Using temple 0.7.5
Using slim 3.0.2
Using slim-rails 3.0.1
Using spring 1.3.1
Using spring-commands-rspec 1.0.4
Using sucker_punch 1.3.2
Using thin 1.6.3
Using turbolinks 2.5.3
Using uglifier 2.7.0
Using web-console 2.0.0
Your bundle is complete!
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    composer  Updating gem paths.
    composer  Stage Two (running recipe 'stage_two' callbacks).
    composer  importing html2haml and haml2slim conversion tools
locale
gems
        gems  recipe stage two
        gems  configuring database
      remove    config/database.yml
      create    config/database.yml
      option  Username for PostgreSQL?(leave blank to use the app name) danny
      option  Host for PostgreSQL in database.yml? (leave blank to use default socket connection) 
        gsub    config/database.yml
      option  Password for PostgreSQL user danny? test
        gsub    config/database.yml
        gems  set config/database.yml for username/password danny/test
        gsub    config/database.yml
        gsub    config/database.yml
        gsub    config/database.yml
      option  Okay to drop all existing databases named cookbook? 'No' will abort immediately! (y/n) y
         run    bundle exec rake db:drop from "."
         run    bundle exec rake db:create:all from "."
cookbook_production already exists
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: create database" from "."
gems
        gems  recipe stage two
        gems  running generators
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: generators" from "."
On branch master
nothing to commit, working directory clean
tests
       tests  recipe stage two
       tests  recipe installing RSpec
    generate    testing:configure rspec -f
         run  rm -rf test/ from "."
    generate  rspec:install
      create  .rspec
      create  spec
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
      insert  .rspec
      insert  .rspec
        gsub  .rspec
      insert  config/application.rb
      create  spec/support/capybara.rb
        gsub  spec/rails_helper.rb
        gsub  spec/rails_helper.rb
      create  spec/support/database_cleaner.rb
      create  spec/support/factory_girl.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: testing framework" from "."
email
       email  recipe stage two
      insert    config/environments/development.rb
      insert    config/environments/production.rb
        gsub    config/environments/production.rb
      insert    config/environments/development.rb
      insert    config/environments/production.rb
        gsub    config/environments/development.rb
        gsub    config/environments/production.rb
        gsub    config/environments/development.rb
        gsub    config/environments/production.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: set email accounts" from "."
devise
      devise  recipe stage two
        gsub    config/initializers/filter_parameter_logging.rb
    generate    devise:install
      create  config/initializers/devise.rb
      create  config/locales/devise.en.yml
===============================================================================

Some setup you must do manually if you haven't yet:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. If you are deploying on Heroku with Rails 3.2 only, you may want to set:

       config.assets.initialize_on_precompile = false

     On config/application.rb forcing your application to not access the DB
     or load models when precompiling your assets.

  5. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

===============================================================================
    generate    devise user
      invoke  active_record
      create    db/migrate/20150210064002_devise_create_users.rb
      create    app/models/user.rb
      invoke    rspec
      create      spec/models/user_spec.rb
      invoke      factory_girl
      create        spec/factories/users.rb
      insert    app/models/user.rb
       route  devise_for :users
    generate    migration AddNameToUsers name:string
      invoke  active_record
      create    db/migrate/20150210064004_add_name_to_users.rb
         run    bundle exec rake db:migrate from "."
== 20150210064002 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0084s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0045s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0186s
== 20150210064002 DeviseCreateUsers: migrated (0.0320s) =======================

== 20150210064004 AddNameToUsers: migrating ===================================
-- add_column(:users, :name, :string)
   -> 0.0009s
== 20150210064004 AddNameToUsers: migrated (0.0010s) ==========================

         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: devise" from "."
omniauth
    omniauth  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: omniauth" from "."
On branch master
nothing to commit, working directory clean
roles
       roles  recipe stage two
    generate    migration AddRoleToUsers role:integer
      invoke  active_record
      create    db/migrate/20150210064009_add_role_to_users.rb
      insert    app/models/user.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add roles to a User model" from "."
frontend
    frontend  recipe stage two
    generate    layout:install bootstrap3 -f
      remove  app/assets/stylesheets/application.css
      create  app/assets/stylesheets/application.css.scss
      create  app/assets/stylesheets/framework_and_overrides.css.scss
       force  app/assets/javascripts/application.js
      remove  app/assets/stylesheets/simple.css
      remove  app/assets/stylesheets/foundation_and_overrides.css.scss
      append  app/assets/stylesheets/framework_and_overrides.css.scss
      remove  app/views/layouts/application.html.erb
      create  app/views/layouts/application.html.slim
      create  app/views/layouts/_messages.html.slim
      create  app/views/layouts/_navigation.html.slim
      create  app/views/layouts/_navigation_links.html.erb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: front-end framework" from "."
pages
       pages  recipe stage two
    generate    pages:users -f
      create  app/views/users/_user.html.erb
      create  app/views/users/index.html.erb
      create  app/views/users/show.html.erb
    generate  pages:home -f
      create  app/views/visitors/index.html.erb
      create  app/controllers/visitors_controller.rb
      insert  config/routes.rb
      create  spec/features/visitors/home_page_spec.rb
       force  app/views/visitors/index.html.erb
      create  app/controllers/users_controller.rb
      insert  config/routes.rb
      create  config/initializers/devise_permitted_parameters.rb
     prepend  app/views/users/_user.html.erb
      insert  app/views/users/show.html.erb
    generate    pages:roles -f
       force  app/views/users/_user.html.erb
       force  app/controllers/users_controller.rb
    generate    layout:navigation -f
   identical  app/views/layouts/_navigation_links.html.erb
      append  app/views/layouts/_navigation_links.html.erb
      append  app/views/layouts/_navigation_links.html.erb
      create  spec/features/visitors/navigation_spec.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add pages" from "."
analytics
   analytics  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add analytics" from "."
On branch master
nothing to commit, working directory clean
extras
      extras  recipe stage two
        gsub    public/robots.txt
        gsub    public/robots.txt
    composer  Stage Three (running recipe 'stage_three' callbacks).
rails_signup_download
  rails_signup_download  recipe stage three
      remove    config/initializers/active_job.rb
      create    config/initializers/active_job.rb
      remove    app/models/user.rb
      create    app/models/user.rb
      remove    app/controllers/visitors_controller.rb
      create    app/controllers/visitors_controller.rb
      remove    app/controllers/products_controller.rb
      create    app/controllers/products_controller.rb
      remove    app/jobs/mailing_list_signup_job.rb
      create    app/jobs/mailing_list_signup_job.rb
      remove    app/views/visitors/index.html.erb
      remove    app/views/visitors/index.html.slim
https://raw.github.com/RailsApps/rails-composer/master/composer.rb:224:in `html_to_slim': uninitialized constant Haml::HTML (NameError)
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:195:in `copy_from_repo'
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:723:in `block in apply'
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2600:in `call'
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2600:in `block in apply'
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2600:in `each'
	from https://raw.github.com/RailsApps/rails-composer/master/composer.rb:2600:in `apply'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/actions.rb:223:in `instance_eval'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/actions.rb:223:in `apply'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/railties-4.2.0/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/railties-4.2.0/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/danny/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/danny/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/railties-4.2.0/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/danny/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/danny/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/bin/rails:23:in `load'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/bin/rails:23:in `<main>'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/bin/ruby_executable_hooks:15:in `eval'
	from /home/danny/.rvm/gems/ruby-2.2.0@cookbook/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dannyvanhoof** [comment]
Seems (as expected) related to my choice for slim. Also haml as options doesn't work. Opting for erb makes the generator run without problems!

**Comment by DanielKehoe** [comment]
It seems html2haml is failing when attempting to convert the file ```app/views/visitors/index.html.erb```. I investigated and the conversion works when using html2haml on the command line.

**Comment by kevinjalbert** [comment]
I have a similar issue when using `rails-stripe-checkout` with *slim*.

**Comment by pyrabbit** [comment]
I was having this same issue when generating a rails-mailinglist-activejob with Haml as the templating engine. I forked composer and made some changes to composer.rb and it fixed the issue... Haml::HTML needs to be Html2haml::HTML

**Comment by DanielKehoe** [comment]
This issue is now resolved with https://github.com/RailsApps/rails-composer/commit/8e341db6d3c8b1c8200a00ee79a8d9d45b9fdcdb thanks to the contribution by @pyrabbit.
