### ISSUE TITLE
using Slim template engine will raise a error

### ISSUE THREAD

**Issue by MofeLee** [RailsApps/rails-composer#224]
![2015-04-27 09 37 23](https://cloud.githubusercontent.com/assets/5069410/7340479/24186af6-ecc1-11e4-9f52-86b80b017fbc.png)

![2015-04-27 09 38 29](https://cloud.githubusercontent.com/assets/5069410/7340486/3249278c-ecc1-11e4-9e2a-8894bd5dc109.png)

**Comment by nikolaevav** [comment]
I also received an error with Haml :
The template [https://raw.github.com/RailsApps/rails-composer/master/composer.rb] could not be loaded. Error: No such file or directory @ rb_sysopen - /home/nik/myapp/app/views/layouts/application.html.erb

/myapp/app/views/layouts $ ls
application.html.haml  _messages.html.haml  _navigation.html.haml  _navigation_links.html.erb

**Comment by DanielKehoe** [comment]
Thanks for bringing this to my attention. I added an option to disable Turbolinks. I neglected to handle the Haml and Slim cases. I've fixed this is the current release of Rails Composer.
