### ISSUE TITLE
Rails 4 / Mysql2 incompatibility

### ISSUE THREAD

**Issue by jbogatay** [RailsApps/rails-composer#235]
Rails 4 doesn't play nice with the latest mysql2 gem.  (0.4.x).    You need to lock the version down to 0.3.x  (currently 0.3.20).

**Comment by alexponi** [comment]
You can see pull request #234 opened on 15 Sep too.

**Comment by DanielKehoe** [comment]
The Rails bug that breaks the latest mysql2 gem. (0.4.x).
https://github.com/rails/rails/issues/21544

**Comment by DanielKehoe** [comment]
I've made the change to the rails_apps_composer gem:
RailsApps/rails_apps_composer@e3e0872
and generated a new version of the rails_composer script.
