### ISSUE TITLE
Bootstrap Templates Option Missing

### ISSUE THREAD

**Issue by jhstephenson** [RailsApps/rails-composer#237]
Did something happen to the templates option? I just created a new application and it never came up.

**Comment by DanielKehoe** [comment]
What were the options you chose? You can show me the contents of your README file which will show your selections.

You must select Bootstrap 3.3 as your front-end framework of you won't get the template options.

**Comment by jhstephenson** [comment]
Never mind, I figured it out.

Apparently I can't read.
