### ISSUE TITLE
Does Rails Composer support Rails 5?

### ISSUE THREAD

**Issue by squaresurf** [RailsApps/rails-composer#242]
A follow up question is what would it take to always use the latest version of Rails?

**Comment by DanielKehoe** [comment]
Install the latest stable version of Rails and Rails Composer will build an app with that version if that Rails gem is in the environment.

If you run Rails Composer with Rails 5, you can build a Rails 5 app. However, some gems will not work with Rails 5 (for example, HighVoltage).

**Comment by squaresurf** [comment]
Awesome. Thank you for your answer. Why do the docs specify that Rails 4.2 is required? Is that the minimum version then?

**Comment by kevinelliott** [comment]
@squaresurf This project is essentially dead (sadly), that's why.

**Comment by DanielKehoe** [comment]
@kevinelliott really? why do you say the project is dead?

**Comment by kevinelliott** [comment]
@DanielKehoe Just seems like the pace has slowed down *tremendously*. Very few updates. No official Rail5 support. No Rails 5 related generators. No Bootstrap 4 support. Commits drastically lower.

It's obviously not completely abandoned, but after seeing you not be able to gain the funding necessary to push forward (I contributed!) it seems like the community is losing steam behind it too.

To be honest *and* fair, I sincerely hope that I am wrong, and that big things are planned and engaged for the project. I really love what it stands for, and it has saved me tremendous time in the past. And I am not trying to insult when I write these things, so apologies for any tone that might have come off on my statement.

**Comment by DanielKehoe** [comment]
Yes, it's been difficult for me to keep up without funding while doing consulting projects to keep myself going. And it seems the Rails community is moving on to many other things. But I'll keep the project going as best I can. Thanks for expressing your appreciation for the project and I hope I can do better. Maybe some updates soon.

**Comment by DanielKehoe** [comment]
I've completed a round of updates to Rails Composer. See the [RailsApps blog](http://blog.railsapps.org/). It fully supports Rails 5.

**Comment by kevinelliott** [comment]
Just wanted to chime in and say that I really appreciate all of the updates! I'm so happy that there is still a sense of dedication to the project, and I really appreciated the responses over the last 6 months or so since first raising the issue.

As always, let me know what I can do to help and I will do whatever is in my power.

Cheers!

**Comment by DanielKehoe** [comment]
Yay! The appreciation is what keeps it alive.
