### ISSUE TITLE
Selecting SendGrid for sending emails still results in user#subscribe implemented with MailChimp 

### ISSUE THREAD

**Issue by secondstreetmedia** [RailsApps/rails-composer#251]
When using rails-composer to generate an app based upon the RailsApp example application "rails-stripe-membership-saas", I chose SendGrid for email support, yet the `subscribe` method in the Devise `user.rb` model file is implemented with Gibbon and MailChimp.

**app/models/user.rb**

    def subscribe
      mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
      list_id = Rails.application.secrets.mailchimp_list_id
      result = mailchimp.lists(list_id).members.create(
        body: {
          email_address: self.email,
          status: 'subscribed'
      })
      Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
    end

Perhaps this is actually correct if the subscribe method is simply an example intended to represent the addition of a user to a subscription of any kind. If not, and it is intended to add a new user to a mailing list that exists with the email support provider chosen, then it seems this method should be implemented with the appropriate code for that provider.

**Comment by DanielKehoe** [comment]
The code is based on the [rails-mailinglist-activejob](https://github.com/RailsApps/rails-mailinglist-activejob) example application. MailChimp is used for mailing list subscription management (broadcast mail). It is just example code. SendGrid is used for transactional mail. You can change the example as you wish.

**Comment by secondstreetmedia** [comment]
Makes total sense.  Thanks!
