### ISSUE TITLE
secrets.yml is not included in the recommended .gitignore file

### ISSUE THREAD

**Issue by RobertBMerriman** [RailsApps/rails-composer#252]
secrets.yml is not included in the recommended .gitignore file

**Comment by DanielKehoe** [comment]
I'd like to know why *secrets.yml* should be included in the *.gitignore* file.

In my book, [Learn Ruby on Rails](http://learn-rails.com/learn-ruby-on-rails.html) I advise developers to use Unix environment variables to set sensitive information such as login credentials. Then refer to Unix environment variables in the *secrets.yml* file. An application is not complete without the *secrets.yml* file and typically it cannot run without it, so it cannot be deployed to Heroku etc. without it. So it seems the *secrets.yml* file should be included in a git repo.

If you have another viewpoint on this issue, I'd like to hear it.

**Comment by DanielKehoe** [comment]
Lack of response to my query for more information so I'm closing the issue. If you can make the case for including *secrets.yml* in the *.gitignore file*, feel free to reopen.

**Comment by bradical** [comment]
I was curious about this too. If `secrets.yml` is under version control what sort of stuff would you put in it? References to environment variables? Anything static that you would include?

**Comment by DanielKehoe** [comment]
Yes, typically it is references to environment variables for credentials. Also it can be a place for configuration variables that do not have to secret (for example, an admin email address).

Rails 5.2 has a new approach for encrypting credentials and ```secrets.yml``` is superseded but can still be used.

**Comment by DanielKehoe** [comment]
Yes @bradical, that's a good example. The name of the file ```secrets.yml``` is no longer appropriate but if you can overlook the misnaming, it is useful.

**Comment by bradical** [comment]
So at that point it’s a bit like figaro’s application.yml but under version
control (which is a good thing in my case!). Aside from fígaro, envvar or
this secrets.yml, is there some other Rails suggested mechanism for
managing non-secret, environment specific variables under source control?
The files in environments look promising but I wasn’t seeing a clear way to
declare constants.
