### ISSUE TITLE
File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by zhikar** [RailsApps/rails-composer#257]
When i run 
rails new obboy_site -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb,
and start with 'rails s', i got  error.

ruby 2.3.0
rails 4.2.6

`
Sass::SyntaxError at /

File to import not found or unreadable: bourbon.
Load paths:
  /Users/chenyuquan/workspaces/obboy/obboy_site/app/assets/images
  /Users/chenyuquan/workspaces/obboy/obboy_site/app/assets/javascripts
  /Users/chenyuquan/workspaces/obboy/obboy_site/app/assets/stylesheets
  /Users/chenyuquan/workspaces/obboy/obboy_site/vendor/assets/javascripts
  /Users/chenyuquan/workspaces/obboy/obboy_site/vendor/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/administrate-0.2.2/app/assets/images
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/administrate-0.2.2/app/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/administrate-0.2.2/app/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/selectize-rails-0.12.2/vendor/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/selectize-rails-0.12.2/vendor/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/normalize-rails-3.0.3/vendor/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/neat-1.8.0/app/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/momentjs-rails-2.11.1/vendor/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/datetime_picker_rails-0.0.7/app/assets/fonts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/datetime_picker_rails-0.0.7/app/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/datetime_picker_rails-0.0.7/app/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/jquery-rails-4.1.1/vendor/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/coffee-rails-4.1.1/lib/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/bootstrap-sass-3.3.6/assets/javascripts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/bootstrap-sass-3.3.6/assets/fonts
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/bootstrap-sass-3.3.6/assets/images
  /Users/chenyuquan/.rvm/gems/ruby-2.3.0/gems/bootstrap-sass-3.3.6/assets/stylesheets
`

**Comment by DanielKehoe** [comment]
Have you added the Bourbon gem to your Gemfile? Because it cannot be found, Ordinarily, that is not a gem installed by Rails Composer so perhaps you added it?

**Comment by zhikar** [comment]
Here is my Gemfile.

```
source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'administrate'
gem 'bootstrap-sass'
gem 'devise'
gem 'high_voltage'
gem 'mysql2', '~> 0.3.18'
gem 'pundit'
gem 'simple_form'
group :development do
  gem 'better_errors'
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end

gem 'puma'
```

**Comment by zhikar** [comment]
when i add bourbon gem , it fixed.   thanks.
`gem 'bourbon'`
