### ISSUE TITLE
Generated Gemfile contains a syntax error

### ISSUE THREAD

**Issue by pconrad** [RailsApps/rails-composer#261]
Each time I run rails composer [EDIT: with Rails 5.0.1 only---see later comments], the created Gemfile starts with these six lines (which contain a syntax error in lines 2-5):

```
source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "
  "https://github.com/
end
ruby '2.3.3'
```

The result is that at the end of the process when `bundle install` is being run, the syntax error is reported thus:

```
[!] There was an error parsing `Gemfile`: syntax error, unexpected tIDENTIFIER, expecting keyword_end -   "https://github.com/
        ^
```

My workaround has been to simply delete lines 2-5, leaving these lines, and then everything appears to work normally.

```
source 'https://rubygems.org'
ruby '2.3.3'
```

My environment is MacOS 10.12.2, with rvm 1.28.0.  The error occurs regardless of which choices I make in the rails composer dialog.  I tried several, including the most basic, i.e....

```
option  Build a starter application?
    1)  Build a RailsApps example application
...
option  Choose a starter application.
    1)  learn-rails
```

... as well as several other of the more advanced options.

Thank you for your work on Rails Composer--and apologies if this is an error in my setup rather than a bug.

**Comment by pconrad** [comment]
This appears to be the same as the closed issue: #260    The author of that issue closed it by saying the error doesn't happen for the combination of ruby-2.3.0 and rails-4.2.6.  In my case, I'm using ruby-2.3.3 and rails-5.0.1   I'll see whether I can pinpoint which combinations have (and do not have) the error.

**Comment by pconrad** [comment]
The error does occur with ruby-2.3.0 and rails 5.0.1

```
cd myapp
mkdir myapp
rvm use ruby-2.3.0@myapp --ruby-version --create
gem install rails
rails new . -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
```

**Comment by pconrad** [comment]
Can confirm: error does NOT happen for ruby-2.3.0 and rails 4.2.6.  First three lines of generated Gemfile are, in that case:

```
source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '4.2.6'
```

A colleague reports not having the problem with ruby-2.3.0 and rails-5.0.0.  Checking that combination now...

**Comment by pconrad** [comment]
CONFIRMED: does not happen with ruby-2.3.0 and rails 5.0.0.   Will now see whether the culprit is ruby-2.3.3 or rails 5.0.1

Here is the start of the Gemfile generated for ruby-2.3.0 and rails 5.0.0.
```
source 'https://rubygems.org'
ruby '2.3.0'
gem 'rails', '~> 5.0.0'
```

**Comment by pconrad** [comment]
Confirmed that ruby-2.3.3 and rails-5.0.0 works just fine.  It appears that rails 5.0.1 may be the culprit.

```
 570  mkdir myapp
  571  cd myapp
  572  rvm use ruby-2.3.3
  573  rvm gemset create rails-5.0.0
  574  rvm gemset use rails-5.0.0
  575  gem install rails -v 5.0.0
  576  rails --version
  577  rails new . -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
```

**Comment by pconrad** [comment]
CONFIRMED: rails 5.0.1 is the culprit.  

The error is absent with ruby-2.3.3 and rails-5.0.0, but present with ruby-2.3.3. and rails-5.0.1

Workaround for now: don't use rails-5.0.1---stick with 5.0.0

```
 581  mkdir myapp
  582  cd myapp
  583  rvm use ruby-2.3.3
  584  rvm gemset create rails-5.0.1
  585  rvm gemset use rails-5.0.1
  586  gem install rails -v 5.0.1
  587  rails new . -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
```

**Comment by DanielKehoe** [comment]
@pconrad Thanks for bringing this to my attention. Rails 5.0.1 broke Rails Composer. Made a small change to the regex that cleans up comments in the Gemfile and it is now fixed with RailsApps/rails_apps_composer@1e247ce.

**Comment by pconrad** [comment]
Thanks for the fix @DanielKehoe and for your work on Rails Composer

**Comment by tomelam** [comment]
@pconrad Thanks for narrowing down this problem.
@DanielKehoe Thanks again and again for your free software contributions, tutorials, and books.
