### ISSUE TITLE
The page "Managing Rails Versions and Gems" gives no good, safe configuration info for the example apps

### ISSUE THREAD

**Issue by tomelam** [RailsApps/rails-composer#263]
http://railsapps.github.io/managing-rails-versions-gems.html
says that "For the example apps it [the Ruby version] should be version 2.2.0."
It says "For the example apps it [the RubyGems system] should be version 1.8.17 or newer."
It says "For the example apps it [the Rails version] should be version 3.2."
It says "For apps built with Rails 3.2, use rake 0.9.2.2 or newer."

Following these recommendations produces an error with Rails Composer. Just before the error, Rails Composer prints "You are using Rails version 3.2.0 which is not supported. Use Rails 4.1 or newer."

**Comment by tomelam** [comment]
Even after setting up ruby and an rvm gemset so I get this:
    $ ruby -v
    ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin16]
    $ rails -v
    Expected string default value for '--rc'; got false (boolean)
    Rails 4.1.0
the devise gem with its confirmable module causes problems:
    run    bundle exec rake db:migrate from "."
    /Users/tom/.rvm/gems/ruby-2.2.0@rails41/gems/activesupport-4.1.0/lib/active_supp
ort/values/time_zone.rb:285: warning: circular argument reference - now
             run    bundle exec rake db:seed from "."
    /Users/tom/.rvm/gems/ruby-2.2.0@rails41/gems/activesupport-4.1.0/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
    rake aborted!
    NoMethodError: undefined method `confirm!' for #<User:0x007fd666d94380>
    /Users/tom/.rvm/gems/ruby-2.2.0@rails41/gems/activemodel-4.1.0/lib/active_model/attribute_methods.rb:435:in `method_missing'

**Comment by DanielKehoe** [comment]
@tomelam Thanks for pointing out that the instructions in that old article are outdated. I've updated the page to eliminate references to specific versions.
