### ISSUE TITLE
failed to @extend ".text-xs-center"

### ISSUE THREAD

**Issue by mhoskiso** [RailsApps/rails-composer#264]
XS is no longer available for Bootstrap 4. Replacing text-xs with text-sm for now.

https://github.com/twbs/bootstrap/issues/21698

**Comment by Schwad** [comment]
@mhoskiso has this been resolved in the latest Rails-Composer? If not, are you willing to submit a PR for @DanielKehoe to review?

**Comment by mhoskiso** [comment]
Yes, looks like this was fixed here:
https://github.com/RailsApps/rails-bootstrap/commit/c58c3322ac6f3cd33d55697a5fdf3131e78a4aa5#diff-efe0beda23100b8feac9aa141242373b
