### ISSUE TITLE
FactoryGirl is now FactoryBot

### ISSUE THREAD

**Issue by WizKidsGames** [RailsApps/rails-composer#275]
As of a month ago, FactoryGirl is now FactoryBot. This breaks a lot of the generators. I'll see if I can throw together a pull request fixing this.

**Comment by greenplastik** [comment]
Looks like this happens when you add Rspec module and Devise module. I think it's something with how Devise generates the user?

```
 generate    devise user
      invoke  active_record
      create    db/migrate/20171130214402_devise_create_users.rb
      create    app/models/user.rb
      invoke    rspec
      create      spec/models/user_spec.rb
       error      factory_girl [not found]
```

**Comment by gpinkham** [comment]
@WizKidsGames @greenplastik 
curious if you were able to get the specs to pass?     maybe it was a wrong assumption but I thought creating the app from composer and immediately running the specs that they would pass..  (after migrating the DB and changing FactoryGirl to FactoryBot of course)..

**Comment by DanielKehoe** [comment]
I've updated the [rails_apps_testing](https://github.com/RailsApps/rails_apps_testing) gem and released a new version of Rails Composer. Could you take a look and see if the issue is resolved. Please reopen the issue if there's still a problem.

**Comment by greenplastik** [comment]
Issue is resolved. Thanks!
